# # MINIO
export SERVER_IP=124.221.190.158
export MINIO_PORT=9000
export MINIO_ENDPOINT=$SERVER_IP:$MINIO_PORT
export MINIO_ACCESS_KEY=iR1BteCtymOsJ7rY
export MINIO_SECRET_KEY=SMDeqEnnKdOvRt1hgbHzE5PmG4uhAPbf
export MINIO_BUCKET=videos-and-covers

# # MYSQL
export MYSQL_HOST=$SERVER_IP
export MYSQL_PORT=43360
export MYSQL_USER=dy_test
export MYSQL_PASSWD=2NrYRM4xeRFZiMn8
export MYSQL_DATABASE=dy_test

# # REDIS
export REDIS_HOST=$SERVER_IP
export REDIS_PORT=62379
export REDIS_AUTH=dytest#5

# # todo 启动后端服务器