set SERVER_IP=124.221.190.158
set MINIO_PORT=9000
set MINIO_ENDPOINT=%SERVER_IP%:%MINIO_PORT%
set MINIO_ACCESS_KEY=B5FbCguhFrJPKzhz
set MINIO_SECRET_KEY=UIZYz7BF5dadrqbkOjWxc3hRVg7xCM2D
set MINIO_BUCKET=videos-and-covers