// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/wanyuyaoxiao/EasyDouYin/simple-demo/service"
)

func main() {
	go service.RunMessageServer()
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))
	customizedRegister(h)
	h.Spin()
}
