// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/qiong-14/EasyDouYin/biz/router"
	"github.com/qiong-14/EasyDouYin/dal"
	"github.com/qiong-14/EasyDouYin/middleware"
	"github.com/qiong-14/EasyDouYin/service"
)

func main() {
	go service.RunMessageServer()
	dal.Init()
	middleware.Init(context.Background())
	middleware.InitJwt()
	h := server.Default(server.WithHostPorts("0.0.0.0:8080"))
	router.Register(h)
	h.Spin()
}
