// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/qiong-14/EasyDouYin/biz/handler"
	"github.com/qiong-14/EasyDouYin/mw"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.Static("/static", "./publish")
	r.GET("/ping", handler.Ping)
	appRouter := r.Group("/douyin")
	// basic apis
	appRouter.GET("/feed/", handler.Feed)
	appRouter.POST("/publish/action/", mw.LoginAuthentication(), handler.Publish)
	appRouter.GET("/publish/list/", mw.LoginAuthentication(), handler.PublishList)
	appRouter.GET("/user/", mw.LoginAuthentication(), handler.UserInfo)
	appRouter.POST("/user/register/", handler.Register)
	appRouter.POST("/user/login/", handler.Login)

	// extra apis - I
	appRouter.POST("/favorite/action/", mw.LoginAuthentication(), handler.FavoriteAction)
	appRouter.GET("/favorite/list/", mw.LoginAuthentication(), handler.FavoriteList)
	appRouter.POST("/comment/action/", mw.LoginAuthentication(), handler.CommentAction)
	appRouter.GET("/comment/list/", mw.LoginAuthentication(), handler.CommentList)
	// extra apis - II
	appRouter.POST("/relation/action/", mw.LoginAuthentication(), handler.RelationAction)
	appRouter.GET("/relation/follow/list/", mw.LoginAuthentication(), handler.FollowList)
	appRouter.GET("/relation/follower/list/", mw.LoginAuthentication(), handler.FollowerList)
	appRouter.GET("/relation/friend/list/", mw.LoginAuthentication(), handler.FriendList)
	appRouter.GET("/message/chat/", mw.LoginAuthentication(), handler.MessageChat)
	appRouter.POST("/message/action/", mw.LoginAuthentication(), handler.MessageAction)
}
