// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/qiong-14/EasyDouYin/biz/handler"
	"github.com/qiong-14/EasyDouYin/middleware"
)

// Register registers routers
func Register(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.Static("/static", "./publish")

	appRouter := r.Group("/douyin")
	appRouter.GET("/feed/", handler.Feed)
	appRouter.POST("/user/register/", handler.Register)
	appRouter.POST("/user/login/", middleware.JwtMiddleware.LoginHandler)
	appRouter.GET("/ping", middleware.JwtMiddleware.MiddlewareFunc(),handler.Ping)
	
	// basic apis
	
	appRouter.POST("/publish/action/", middleware.JwtMiddleware.MiddlewareFunc(), handler.Publish)
	appRouter.GET("/publish/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.PublishList)
	appRouter.GET("/user/", middleware.JwtMiddleware.MiddlewareFunc(), handler.UserInfo)
	

	// extra apis - I
	appRouter.POST("/favorite/action/", middleware.JwtMiddleware.MiddlewareFunc(), handler.FavoriteAction)
	appRouter.GET("/favorite/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.FavoriteList)
	appRouter.POST("/comment/action/", middleware.JwtMiddleware.MiddlewareFunc(), handler.CommentAction)
	appRouter.GET("/comment/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.CommentList)
	// extra apis - II
	appRouter.POST("/relation/action/", middleware.JwtMiddleware.MiddlewareFunc(), handler.RelationAction)
	appRouter.GET("/relation/follow/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.FollowList)
	appRouter.GET("/relation/follower/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.FollowerList)
	appRouter.GET("/relation/friend/list/", middleware.JwtMiddleware.MiddlewareFunc(), handler.FriendList)
	appRouter.GET("/message/chat/", middleware.JwtMiddleware.MiddlewareFunc(), handler.MessageChat)
	appRouter.POST("/message/action/", middleware.JwtMiddleware.MiddlewareFunc(), handler.MessageAction)
}
