// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/qiong-14/EasyDouYin/biz/handler"
	"github.com/qiong-14/EasyDouYin/mw"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.Static("/static", "./publish")

	appRouter := r.Group("/douyin")
	appRouter.GET("/feed/", handler.Feed)
	appRouter.POST("/user/register/", handler.Register)
	appRouter.POST("/user/login/", mw.JwtMiddleware.LoginHandler)
	appRouter.GET("/ping",mw.JwtMiddleware.MiddlewareFunc(),handler.Ping)
	
	// basic apis
	
	appRouter.POST("/publish/action/",mw.JwtMiddleware.MiddlewareFunc(), handler.Publish)
	appRouter.GET("/publish/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.PublishList)
	appRouter.GET("/user/",mw.JwtMiddleware.MiddlewareFunc(), handler.UserInfo)
	

	// extra apis - I
	appRouter.POST("/favorite/action/",mw.JwtMiddleware.MiddlewareFunc(), handler.FavoriteAction)
	appRouter.GET("/favorite/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.FavoriteList)
	appRouter.POST("/comment/action/",mw.JwtMiddleware.MiddlewareFunc(), handler.CommentAction)
	appRouter.GET("/comment/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.CommentList)
	// extra apis - II
	appRouter.POST("/relation/action/",mw.JwtMiddleware.MiddlewareFunc(), handler.RelationAction)
	appRouter.GET("/relation/follow/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.FollowList)
	appRouter.GET("/relation/follower/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.FollowerList)
	appRouter.GET("/relation/friend/list/",mw.JwtMiddleware.MiddlewareFunc(), handler.FriendList)
	appRouter.GET("/message/chat/",mw.JwtMiddleware.MiddlewareFunc(), handler.MessageChat)
	appRouter.POST("/message/action/",mw.JwtMiddleware.MiddlewareFunc(), handler.MessageAction)
}
